const INVEST: &str = include_str!("../../skills/okx-defi/references/invest.md");
const INVEST_TROUBLESHOOTING: &str =
    include_str!("../../skills/okx-defi/references/invest-troubleshooting.md");
const WALLET_TROUBLESHOOTING: &str =
    include_str!("../../skills/okx-agentic-wallet/references/wallet-troubleshooting.md");

#[test]
fn defi_transaction_fields_must_be_forwarded_verbatim() {
    assert!(INVEST.contains("Prepared transaction data is opaque"));
    assert!(INVEST.contains(
        "use `to`, `serializedData`, and any applicable value field directly from that same entry"
    ));
    assert!(
        INVEST.contains("Never recreate, edit, truncate, pad, concatenate, re-encode, or annotate")
    );
    assert!(INVEST.contains("Pass the complete `serializedData`"));
}

#[test]
fn generated_calldata_errors_require_regeneration_not_repair() {
    assert!(INVEST_TROUBLESHOOTING.contains("-32602 Invalid params"));
    assert!(INVEST_TROUBLESHOOTING.contains("without a txHash"));
    assert!(INVEST_TROUBLESHOOTING
        .contains("Never inspect, edit, re-encode, or resubmit the old `serializedData`"));
    assert!(INVEST_TROUBLESHOOTING
        .contains("Rerun the documented DeFi preparation flow that produced `dataList`"));
    assert!(INVEST_TROUBLESHOOTING.contains("use only the newly returned transaction fields"));
    assert!(
        WALLET_TROUBLESHOOTING.contains("never repair a payload generated by another CLI command")
    );
}
